name: Generate test plan

on:
  push:
     branches:
      - main
  workflow_dispatch:

jobs:
  generate-test-campaign:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Clean up
      uses: actions/github-script@v3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const projects = await github.projects.listForRepo({
            ...context.repo
          });
          for (let project of projects.data) {
            github.projects.delete({project_id: project.id})
          } 

    - name: Generate Test Campaign
      uses: ./
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    